In [2]:
#1
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Joshua Francisco Array: [66 42 47 34 15 72 79 21 69 66]
Mean: 51.1 Std Dev: 21.403037167654503


In [3]:
#2
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Joshua Francisco's Matrix:
 [[ 2 10 15  2]
 [15  8 15 21]
 [10  5  2 22]]
Row sums: [29 59 39]
Column sums: [27 23 32 45]


In [5]:
#3
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Joshua Francisco's 3D Array:
 [[[ 1  9 14]
  [ 1 14  7]
  [14 20  9]]

 [[ 4  1 21]
  [10  5  9]
  [ 0 17 11]]

 [[ 3 14  8]
  [ 9 17  4]
  [ 2  5  2]]]
Slice[:,1,:]:
 [[ 1 14  7]
 [10  5  9]
 [ 9 17  4]]


In [6]:
#4
import numpy as np
STUDENT_NAME = "Joshua Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Joshua Francisco's Original: [66 42 47 34 15 72 79 21 69 66]
Filtered subset: [42 47 34 15 21]


In [7]:
#5
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[ 2 10]
 [15  2]]
Matrix B:
 [[15  8]
 [15 21]]
A @ B:
 [[180 226]
 [255 162]]
Determinant of A: -146.0


In [8]:
#6
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Joshua Francisco's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [9]:
#7
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Joshua Francisco's Modified 4x4 Array:
 [[ 0 10  0  2]
 [15  8 15 21]
 [ 0  5  0 22]
 [11  6 10  1]]


In [10]:
#8
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Joshua Francisco's Scores: [65 41 46 33 14 71 78 20 68 65]
Grades: ['Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


In [11]:
#9
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[ 2 10 15  2]
 [15  8 15 21]
 [10  5  2 22]]
Flattened: [ 2 10 15  2 15  8 15 21 10  5  2 22]
Transposed:
 [[ 2 15 10]
 [10  8  5]
 [15 15  2]
 [ 2 21 22]]


In [12]:
#10
import numpy as np
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 -1 15]
 [-1 15 -1]
 [15 21 -1]]


In [14]:
#11
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Fancisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

                      Name  Score  YearsCodePro
0  Joshua C. Francisco     69             7
1  Joshua C. Francisco     45            14
2  Joshua C. Francisco     50            20
3  Joshua C. Francisco     37             9
4  Joshua C. Francsico     18             4


In [15]:
#12

import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     68126.0
Master       84276.0
PhD         112316.0
Name: ConvertedComp, dtype: float64


In [16]:
#13
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
2           UK         112316
4      Germany         102919
0  Philippines          83438
1          USA          65633
3       Canada          52814


In [17]:
#14
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID%10]
print(high_exp)

                      Name  YearsCodePro
1  Joshua C. Francisco             9
2  Joshua C. FRancisco            14
4  Joshua C. Francisco            14


In [18]:
#15
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          83438   50-100k
1          65633   50-100k
2         112316  100-150k
3          52814   50-100k
4         102919  100-150k


In [19]:
#16
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          83438  11.331859
1          65633  11.091834
2         112316  11.629072
3          52814  10.874532
4         102919  11.541698


In [20]:
#17
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.644732
ConvertedComp      0.644732       1.000000


In [21]:
#18
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   68126.0   68126.0  21654.438067
1    Master   84276.0   84276.0  26365.183443
2       PhD  112316.0  112316.0           NaN


In [22]:
#19
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          83438      No
1          65633      No
2         112316     Yes
3          52814      No
4         102919      No


In [23]:
#20
import numpy as np
import pandas as pd
STUDENT_NAME = "Joshua C. Francisco"
STUDENT_ID = 3554

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        52814.0   52814
Germany      102919.0  102919
Philippines   83438.0   83438
UK           112316.0  112316
USA           65633.0   65633
